### ISSUE TITLE
Device "eth0" does not exist.怎么处理？

### ISSUE THREAD

**Issue by zhbbo** [MstKenway/iptables-man#1]
请输入数字 [1-9]:1
已经安装iptables，继续...
开始配置 iptables !
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbrplus
net.ipv4.ip_forward = 1
iptables 配置完毕 !
正在安装依赖bind-uitls，用于查询dns
Device "eth0" does not exist.

**Comment by zhbbo** [comment]
root@107-172-xxx-xxx-host:~# ifconfig
ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
我的VPS默认网卡是ens3

**Comment by MstKenway** [comment]
感谢你的反馈。
此后提示用户验证本机IP时可输入n并填入本机IP。
后续会对此问题改进。
